### ISSUE TITLE
TLS preventing Invoke-WebRequest

### ISSUE THREAD

**Issue by Mettra** [Slaynash/MelonLoaderAutoInstaller#2]
When running the auto-installer, all of the `Invoke-WebRequest` were failing with: 
`Invoke-WebRequest : The request was aborted: Could not create SSL/TLS secure channel`.

I don't know if this is a universal solution, but at least for me putting `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;` in front of all the `Invoke-WebRequest` commands in the batch file fixed it.

**Comment by Slaynash** [comment]
Ah thanks, I'll implement it in the installer script

**Comment by Slaynash** [comment]
Fixed in v1.4!
